### ISSUE TITLE
Problem in temp-mails package

### ISSUE THREAD

**Issue by juju-03** [bertigert/temp-mails#2]
Hi Sir,
I tried to use your temporary email package, but I am getting the following error when trying your sample code:

```
PS C:\Users\x> & C:/Users/x/AppData/Local/Programs/Python/Python311/python.exe "c:/Users/x/Downloads/from temp_mails import Tenminemail_com.py"
Traceback (most recent call last):
  File "c:\Users\x\Downloads\from temp_mails import Tenminemail_com.py", line 1, in <module>
    from temp_mails import Tempmail_id
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\site-packages\temp_mails\__init__.py", line 107, in <module>
    from .providers.mailinator_com import Mailinator_com
  File "C:\Users\x\AppData\Local\Programs\Python\Python311\Lib\site-packages\temp_mails\providers\mailinator_com.py", line 89
    "time": f"{time()*1000-data["seconds_ago"]:.0f}",
                                 ^^^^^^^^^^^
SyntaxError: f-string: unmatched '['

```
I tried to fix it myself, changing:
```
"time": f"{time()*1000-data["seconds_ago"]:.0f}",
```
to:
```
"time": f"{time()*1000-data['seconds_ago']:.0f}",
```

but now I got another error:
```
Traceback (most recent call last):
 File "c:\Users\x\Downloads\from temp_mails import Tenminemail_com.py", line 2, in <module>
 from send_email import send_email_sync
ModuleNotFoundError: No module named 'send_email'
```

Can you help me?

**Comment by bertigert** [comment]
Very late response, but heres my answer:

The reason is that youre using a python version lower than 3.12. I fixed your specific issue in the latest update, there are probably other places where it exists.
send_email is an example package/function which can be used to send an email to any address. Youd need to implement your own logic for it (e.g. sign up to something), since theres no generalized way to send an email.
